### ISSUE TITLE
Syntax highlighting for Swift doesn't work

### ISSUE THREAD

**Issue by Boris-Rasin** [matcornic/hugo-theme-learn#154]
For Swift all text inside fences is rendered in the same color.
Works correctly using DocDock theme.

**Comment by matalo33** [comment]
This is by design, highlight.js only ships with support for a few core languages and Swift is not included in this list. Visit https://highlightjs.org/download/ and see which languages are included by default.

If you want to enable Swift support visit the highlightjs download page and select the languages you want to support. Replace `js/highlight.pack.js` and `css/hybrid.css` in the theme with the downloaded versions and you should be good.
