### ISSUE TITLE
Fix Hugo Demo site

### ISSUE THREAD

**Issue by stephlocke** [matcornic/hugo-theme-learn#16]
The Demo button for the preview of this theme does not work. It'd be neat if you could fix so more people use the theme.
http://themes.gohugo.io/theme/hugo-theme-learn/

**Comment by matcornic** [comment]
Hello @stephlocke , thanks for the remark.

This button and the link behind is managed by Hugo, not me.
I had already created an issue on this issue (because it's possible to disable it), but it seems that the button is back. I'll create another one.

If you need to go to the real demo, use the button "Homepage".
