### ISSUE TITLE
Enable linking to a hidden page within another hidden page

### ISSUE THREAD

**Issue by iaktern** [matcornic/hugo-theme-learn#164]
Background: I really like the `hidden` metadata in the front matter as a replacement for `draft`, because that enables me to send my boss a link to a _draft_ page without having him to pull the git project and start the hugo dev server. I often have multiple hidden pages and, as far as I know, my only option to make them visible for navigation is the children shortcode: `{{% children showhidden="true" %}}`

Therefore, it would be nice if the navigation buttons of a hidden page link to the next hidden page, only if the next page in the order is a hidden page. This should not  change the existing behavior that the navigation buttons of a not-hidden page should not link to a hidden page - even if it is the next page in the order. 

(Moreover, it would be cool if the  `hidden` metadata would also work on topmost pages, so that they are not shown in the navigation pane.)

**Comment by matalo33** [comment]
This sounds like possibly a limitation of Hugo rather than this theme. Instead of trying to have Hugo handle your draft pages could I suggest an alternative?

I maintain a private hugo website using this theme at my employer. We have a deployment pipeline configured so that whenever a branch is pushed to the git server a new copy of the website is published at a temporary URL using the git hash. For example:

`https://staging.mywebsite.com/2b79e4b/index.html`

Once the website is published at a temporary URL we open a pull request to review the code, and the reviewers can see a complete copy of the website to validate the markdown is rendering correctly.

This theme and others who forked it use Netlify to provide this functionality. I rolled something custom, actually there's a blog post about this going out soon. I'll provide the link when it's out.
