### ISSUE TITLE
Enable per-PR preview builds in netlify

### ISSUE THREAD

**Issue by matalo33** [matcornic/hugo-theme-learn#191]
https://app.netlify.com/sites/learn/settings/deploys

**Comment by pgorod** [comment]
This is a setting in Netlify configuration...

I am getting these PR previews in my site which uses Learn Theme, but I believe this particular setting is not part of the theme, because it depends on how you're deploying the site you build with the theme.

This is an excellent Netlify feature, by the way. Do you think anything else needs to be done in the Theme files for this? Or were you just adding this Issue as a "note to self", as a reminder? :-)

**Comment by matalo33** [comment]
Unsetting the environment variable `HUGO_BASEURL` (was `//learn.netlify.com`) in netlify builds seems to have fixed preview builds. 

I do see an issue with the theme trying to load index.json (for search) without a baseurl. Looking into this before closing ticket but will leave the variable deleted

**Comment by matalo33** [comment]
Excellent, do you give me permission to copy your netlify file?

The original maintainer only configured netlify via the UI and the baseurl was set global, which broke all preview builds.

**Comment by pgorod** [comment]
Sure, go ahead.
