### ISSUE TITLE
use .Site.BaseURL for assets

### ISSUE THREAD

**Issue by ripienaar** [matcornic/hugo-theme-learn#25]
all assets have hardcoded paths like `/css` should be baseurl related

**Comment by matcornic** [comment]
Thanks @ripienaar for your PR :)

Actually, you're not the first to create this specific one. See https://github.com/matcornic/hugo-theme-learn/pull/6 & https://github.com/matcornic/hugo-theme-learn/pull/9 & https://github.com/matcornic/hugo-theme-learn/issues/3

Instead of putting baseurls, you could use the obscure Hugo parameter named `canonifyURLs = true` (as I did in the documentation : https://github.com/matcornic/hugo-learn-doc/blob/master/config.toml#L6 )

But as your are not the first to share this (and I think you won't be the last if this does not change), I will accept your PR. It will be more obvious and straightforward for everybody (cc @nimmaj @fanningert @TimNN)

**Comment by ripienaar** [comment]
oh *thats* what `canonifyURLs` does :) docs really not clear, I saw other themes used the baseurl that seemed a lot more obvious

thanks for the merge and the theme!

**Comment by jehoshua7** [comment]
Despite having the config value of `canonifyurls = true` , this doesn't work when the URI is https://example.com/hugo  (or some other path).
