### ISSUE TITLE
Syntax Highlighting is not enabled for cpp / c in _index.md

### ISSUE THREAD

**Issue by kshitijkorde** [matcornic/hugo-theme-learn#261]
I can see that an earlier commit of hugo-theme-learn had syntax highlighting enabled for cpp in themes/learn/static/js/highlight.pack.js, but now it is not. It has high-lighting enabled for a bunch of other languages like bash, PowerShell, JSON, etc..
Not sure if the support for cpp/c/java can be added in this highlight.pack.js
PS: I am using an older version of **highlight.pack.js (v9.2.0)** which supports cpp highlighting.

**Comment by matalo33** [comment]
Hiya. Instead of supporting all possible languages and shipping a large `highlight.pack.js` only "common" languages are included by default. 

The best way for you to support the languages that matter to you is for you to download your own customised `highlight.pack.js` from https://highlightjs.org/download/ and override the file in your hugo site.

**Comment by kshitijkorde** [comment]
thanks for the quick reply.
