### ISSUE TITLE
Syntax Highlighting not working for JS and Docs don't Document Why

### ISSUE THREAD

**Issue by timpur** [matcornic/hugo-theme-learn#283]
(https://learn.netlify.com/en/cont/markdown/#syntax-highlighting)

![image](https://user-images.githubusercontent.com/7701482/57274389-776a0c00-70de-11e9-9235-9aa5965fe040.png)

As you can see from the above the included `highlightjs` with `hugo-theme-learn` doesn't include JS even though the docs use this as an example ...

Lastly maybe it would be good to document how to include more languages, as this took me a while to figure out. Mainly because of the first issue ^^ but also documenting how to do this would help.

Thanks :)

**Comment by matalo33** [comment]
The default highlight js should contain support for `javascript`. I thought it might be `javascript` and not `js` but looking at the preview build at #294 it doesn't seem to have resolved it.

I'll get a fresh highlight.js included soon.

In the meantime as you've gone through the effort of discovering how to support custom languages would you be able to update the documentation with your findings?

**Comment by kyeotic** [comment]
This bug is confusing me. The highlight shortcode works, and generates server-side html that breaks up the tags and adds inline styles to modify the color. The code fences generate an unstyled `<pre><code>` pair. It seems like this is relying on client-side highlighting, presumably from highlight.js.

```
{{< highlight javascript>}}
import { useQueryParams } from 'raviger'
import qs from 'qs'

export function useCustomQuery() {
  return useQueryParams(qs.parse, qs.stringify)
}
{{< /highlight>}}
```

Produces
![image](https://user-images.githubusercontent.com/1187432/66100250-09c3ee00-e55f-11e9-8549-84790ecd992c.png)

```
```javascript
import { useQueryParams } from 'raviger'
import qs from 'qs'

export function useCustomQuery() {
  return useQueryParams(qs.parse, qs.stringify)
}
``````

Produces

![image](https://user-images.githubusercontent.com/1187432/66100271-1f391800-e55f-11e9-9fcd-2e0b6824643a.png)

Shouldnt these behave the same with?
```
[params]
  pygmentsStyle = "monokai"
  pygmentsCodefences = true
  pygmentsUseClasses = false // ive tried true here, same result
```

**Comment by pgorod** [comment]
I am having the same problem with PHP, and I think I found the issue.

Our ` highlight.pack.js` simply is not including those languages. If you search that file for `registerLanguage` you can see the languages it supports, it's not including PHP, nor JS.

The pack is generated on the highlight.js site, we need to check some checkboxes there to include more languages, and basically we need to be _a lot_ more generous with the selection of languages to include.

**Comment by pgorod** [comment]
I can now confirm the above. I generated a new `highlight.pack.js` with more languages and put it in `static/js` and now my colors are back.
