### ISSUE TITLE
Theme does not support baseurl with path component

### ISSUE THREAD

**Issue by TimNN** [matcornic/hugo-theme-learn#3]
This theme does not support deployment to baseurls which include a path component such as http://username.github.io/repo since assets are referred to as absolute paths.

**Comment by matcornic** [comment]
Actually, I think it does. The documentation of this theme is deployed on a github.io site : https://matcornic.github.io/hugo-learn-doc/basics/what-is-this-hugo-theme/ (base url = https://matcornic.github.io/hugo-learn-doc/). 

Repo of the documentation is here : https://github.com/matcornic/hugo-learn-doc

What is the content of your config.toml ?

**Comment by TimNN** [comment]
[This file](https://github.com/HPI-SWA-Teaching/SWT16-Project-14/blob/00d4c66c635e72c7ac907454389c5a584b2d521f/setup/index.html) (notice the absolute references to resources) was generated from [this hugo setup](https://github.com/HPI-SWA-Teaching/SWT16-Project-14/tree/3a950e624bed6da767b40e269c17a27811c94302/notes) ([`config.toml`](https://github.com/HPI-SWA-Teaching/SWT16-Project-14/blob/3a950e624bed6da767b40e269c17a27811c94302/notes/config.toml)) with the `baseurl` set to `http://HPI-SWA-Teaching.github.io/SWT16-Project-14/` on the command line.

Looking at the `config.toml` of the documentation, would setting `
canonifyurls = true` cause these urls to be rewritten and properly prefixed?

**Comment by matcornic** [comment]
@TimNN Sorry for my late answer, but yes, `canonifyURLs = true` is the right parameter to set ( https://gohugo.io/extras/urls/ ).
You can see it in action with this [index.html](https://github.com/matcornic/hugo-learn-doc/blob/gh-pages/basics/index.html) file, extracted from the gh-pages branch of the learn theme documentation. Every link is automatically prefixed by the baseurl. 

Note : don't forget to set a `baseURL`.

I'll close the issue for now. Because your question is interesting for everyone, I may add a sentence in the documentation ;)

**Comment by jehoshua7** [comment]
#https://github.com/matcornic/hugo-theme-learn/issues/25#issuecomment-873497994
