### ISSUE TITLE
Minor Graphical Issue

### ISSUE THREAD

**Issue by keyolk** [matcornic/hugo-theme-learn#30]
Hi I found some stranges in my page.

See below image
![image](https://cloud.githubusercontent.com/assets/5329850/22000824/4a6d2dec-dbf6-11e6-9c5e-c787fe63c693.png)

When I choose the menu "security" which under the "Container" menu.
Another menu entry "Securiy" also be highlighted and opened, if I checked before.

Any idea why it works like that ?

**Comment by matcornic** [comment]
Haha, it's a funny bug ! 😄 

It's surely because of the path names `container/security`and `security` are similar. But I don't know why this behaviour happens yet. I will look into that, but you can avoid that by setting different folder names for the moment.

**Comment by matcornic** [comment]
It's because of this line : https://github.com/matcornic/hugo-theme-learn/blob/master/layouts/partials/menu.html#L41 and especially `{{if in $page.RelPermalink $first.RelPermalink }}parent{{ end }}`

`security` is **"in"** `container/security` so the `parent` class is set to the menu and you get this weird result.

**Comment by keyolk** [comment]
Yeah~ That was the reason : )

**Comment by matcornic** [comment]
Fixed with #36
