### ISSUE TITLE
What does "chapter = true" do?

### ISSUE THREAD

**Issue by retorquere** [matcornic/hugo-theme-learn#306]
I see that it means that it will have child pages, but does that mean within a section there could be multiple chapters? Is `_index.md` automatically a chapter?

**Comment by pocc** [comment]
Chapter changes the CSS associated with the page. I encourage you to play around with it because you'll see the changes in rendered HTML (and whether you want them or not). I used to use chapters but don't now because it reduces the size of images (to 60% width if I recall correctly?), which was undesirable.

**Comment by matalo33** [comment]
Chapters are an [archetype](https://gohugo.io/content-management/archetypes/#readout) used by this theme, [introduced here in the theme documentation](https://learn.netlify.com/en/basics/installation/).

You can have chapters within chapters.

Yes chapter type pages have their own CSS and theme layout. You can override this CSS if you desire. The best way to do this is to create a ["yours" theme variant](https://learn.netlify.com/en/basics/style-customization/#yours-variant), copy all the CSS from the red / blue / green variant, and make whatever customisations you want.
