### ISSUE TITLE
Using icons (from font-awesome) on the pages

### ISSUE THREAD

**Issue by mpimentel** [matcornic/hugo-theme-learn#32]
When I try to call an icon (using font-awesome) from any of the chapter pages, there is an error parsing the html!
Sample code:
`+++`
`weight = 0`
`title = "Some Chapter title"`
`chapter = true`
`next = "/next/path"`
`icon = "<i class="fa fa-check"></i>"`
`+++`

Am I calling the icon correctly, or should I have a local copy of font-awesome in the project?

**Comment by matcornic** [comment]
Hello,

It should work, font-awesome is included in the theme. So, you may have a pbm somewhere. 

Maybe it's just because of double quotes usage. Try `'<i class="fa fa-check"></i>'` instead of `"<i class="fa fa-check"></i>"` !

And if the issue is still present, I just need some more details:

- Which Hugo version do you use ?
- What is the error ?
- Can you paste here the logs from your browser console ?

**Comment by mpimentel** [comment]
Yes, figured it out after a while! It was a problem with the quotes!
Many thanks!
