### ISSUE TITLE
Update Mermaid

### ISSUE THREAD

**Issue by SaltyYuki** [matcornic/hugo-theme-learn#326]
Hello,

I use Learn for my documentation and Mermaid to produce schema inside
To facilitate the creation of Schema, I need a new available mermaid functionality : https://github.com/knsv/mermaid/issues/916

Can you update mermaid, please?
If not, Is it possible to use a different version of mermaid than the one available in Learn ?

thank you

**Comment by matalo33** [comment]
Please feel free to retrieve the latest version of mermaid and propose the upgrade in a pull request. You should include in the pull request a link to where you obtained the file from so that a reviewer can verify the integrity of the file.

It makes more sense for someone else to propose this change for a maintainer to review rather than have someone make the change directly without review.

If you would rather not propose the change in a pull request you can override your own local version of mermaid by creating the file `static/mermaid/mermaid.js` (note: not `themes/hugo-learn-theme/static/...`)

**Comment by simonwfarrow** [comment]
I have created a pull request for this to update to 8.2.6 - [pull request](https://github.com/matcornic/hugo-theme-learn/pull/327)

**Comment by McShelby** [comment]
Fixed in #443. This issue can be closed
