### ISSUE TITLE
Scroll Issue with Chrome

### ISSUE THREAD

**Issue by alanef** [matcornic/hugo-theme-learn#49]
Your theme is very nice, but Chrome presents a scroll issue.

This issue does not occur in MS Edge or Firefox.

Essentially if you scroll down in Chrome, the page then tries to scroll back up[ to the top.

Clearly a Javascript issue ( disabling JS in chrome make the problem go away ).  Console shows no JS errors.

I tried looking at your code, but you are doing several clever things relating to window height and scroll so couldn't easily identify the exact issue.

**Comment by matcornic** [comment]
Hello @alanef ,

Did you clone the theme recently ? #45 and #46 may cause problems if you did not refresh cache since the update.

Try refreshing cache on your browser (Shift+F5 on Windows, Cmd+R on Mac). This cache issue could be fixed with #47 

By the way, I do not have the problem on my Chrome (58.0.3029.96 (64-bit)).

**Comment by alanef** [comment]
Thanks for getting back to me.

It seems I had quite an old version of the theme,  I used GitLab continuous integration to build and deploy. For some reason, submodiules are the way ti get this running - but I can't recall - some error occurs if you git clone a sub directory.

 By adding 
git submodule update --recursive --remote
before my build, pulls the latest version.

And it works.
