### ISSUE TITLE
Menu items inconsistency

### ISSUE THREAD

**Issue by 0xbaadf00d** [matcornic/hugo-theme-learn#80]
Sometime items from left menu just disappear (tested with Hugo 0.25.1 and 0.29).  I said sometime, cause the issue appear few time (about 1 time / 4 "compilation")

By example I have the following left menu:

```
Book 1
   - Page 1
   - Page 2
   - Page 3
Book 2
   - Chapter 1
         - Page 1
         - Page 2
         - Page 3
   - Chapter 2
         - Page 1
         - Page 2
```

Sometime, when I visit a page (random, issue is not consistent) the left menu remove some links, by example, the above left menu become

```
Book 1
   - Page 1
   - Page 2
   - Page 3
Book 2
   - Chapter 1
         - Page 1
         - Page 2  [VISITED PAGE]
```

![image](https://user-images.githubusercontent.com/1005086/31346240-bd4872d8-ad18-11e7-8920-4ff574521d9d.png)

With `-v` (verbose), I see no warnings or errors during generation...

**Comment by jcw** [comment]
This may be a cache refresh issue - I've been seeing the same on several occasions, but so far a browser refresh seems to fix it. I don't know whether Hugo & this theme use Etags or other page validity checks, maybe the pages need to have shorter expire-by dates or something...

**Comment by matcornic** [comment]
Yeah, it happened to me too once. I rerun `hugo server` and it was OK. 

Maybe it's a cache pbm and configuring your host server with `Cache-Control` header wit no cache (max-age=0) could be a solution.
Maybe it's a problem when Hugo generates the page.

I'll close the issue for now, but don't hesitate to send a message if you'd encounter this issue again. If this happens, try to extract the HTML of the menu in order to check if the submenu is there (but hidden) or not there at all.

**Comment by matcornic** [comment]
Actually the issue has been encountered here to #79
