### ISSUE TITLE
Handling of top-level titles

### ISSUE THREAD

**Issue by pgorod** [matcornic/hugo-theme-learn#98]
Hi,

I'm setting up a new documentation site and I'm using Learn Theme. 

I ran into a problem with a missing Homepage which I reported at Hugo's site:

https://github.com/gohugoio/hugo/issues/4166

I ask if you can please take a minute to read that thread to see what this is about.

So the questions I need to ask here are:
1. Am I correct to say that the Theme is doing some special treatment of top-level title? Or am I simply lost (it's possible!)?
2. Do you think this handling of title-only pages can be improved like **bep** suggests? It's very misleading for site developers.

3. Is it really a good idea to strip content (the top-level headings) from the file and use the `title` from front-matter instead?

I can see my end-users editing the site and getting lost with the particularities of this. I assume the front-matter `title` is what gets used for the sidebar menu entry, and so it makes some sense to use it at the top of the page. But wouldn't it be better to simply leave the document as it is?

Advantages:
- If I want to, can use a different string for the menu entry and for the page title. This might be useful if I need to keep stuff on the menu shorter, for example.
- I can get an automatic process to check and warn me if the front-matter `title` and the main heading on the page are different.
- no special handling of special content to misguide users and create weird situations that look like bugs

Anyway, thanks for everything!

**Comment by matcornic** [comment]
> Am I correct to say that the Theme is doing some special treatment of top-level title? Or am I simply lost (it's possible!)?

It depends.
- In the Homepage of website, you can use top-level titles (see [homepage](https://raw.githubusercontent.com/matcornic/hugo-theme-learn/master/exampleSite/content/_index.en.md) of Learn doc site)
- In [chapter pages](https://learn.netlify.com/en/basics/installation/#create-your-first-chapter-page), you have to use top-level titles for a nice rendering.
- In content pages, top level titles (`# Header 1` in Markdown) are not meant to be used as the `title` title contains the information. In this case, the theme does a single special treatment : it renders automatically the `title` as an `h1` title on top of the content. That's it. You could add other top level titles in the page if you want.

As the doc website is built with Learn Theme, feel free to check the sources (in `exampleSite` folder). You will find many examples of use.

> Do you think this handling of title-only pages can be improved like bep suggests? It's very misleading for site developers.

By `title-only`pages, do you mean `chapter` ones ? In chapter pages, you can have top-level titles.
Content pages are not meant to contain only a title.

> Is it really a good idea to strip content (the top-level headings) from the file and use the title from front-matter instead?

I tried to create a new page with following content and it works as expected. Content is not stripped.

```
---
date: 2016-04-09T16:50:16+02:00
title: Title as frontmatter 
weight: 25
---

# Title as header

```

![image](https://user-images.githubusercontent.com/3520706/35065336-494e1bb8-fbcd-11e7-8a03-3931964a00b4.png)

The theme has no specific code for handling asciidoc or Markdown. It's Hugo itself that handles this. Maybe asciidoc does something special ?

> I can see my end-users editing the site and getting lost with the particularities of this. I assume the front-matter title is what gets used for the sidebar menu entry, and so it makes some sense to use it at the top of the page. But wouldn't it be better to simply leave the document as it is?

The front-matter `title` is indeed used for menu and page title (in the browser tab and breadcrumb too). If you need to have a different title in the menu, use [menuTitle](https://learn.netlify.com/en/cont/pages/#front-matter-configuration).

This follows *convention over configuration* pattern. In most cases, you just need to fill one line: the `title` in Front Matter and everything is automatically synchronised (*convention*). You do it once and don't need to c/c. Then, you have ways to overwrite the behavior when needed, for special cases only (*configuration*)

> If I want to, can use a different string for the menu entry and for the page title. This might be useful if I need to keep stuff on the menu shorter, for example.

See [menuTitle](https://learn.netlify.com/en/cont/pages/#front-matter-configuration).

But I agree that it could have been like this from the beginning. As it's a breaking change, it could break many sites without notice, as the `hugo build` would not fail (so we have to be careful).

> no special handling of special content to misguide users and create weird situations that look like bugs

I understand the struggle, that's why [archetypes](https://learn.netlify.com/en/cont/archetypes/) exist. I will modify them to add more demonstrative examples 😉 

Thanks for using Learn Theme 🙌

**Comment by pgorod** [comment]
Thanks Mathieu for your careful explanation, it's very nice of you! :-)
